### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by afm215** [claroche-r/PnP_LADMM#3]
**Title** : custom_blur_centered.mat is missing.

**Details:** I am trying to run the jupyter notebook, but at custom_blur_centered.mat, it requires custom_blur_centered.mat, which doesn't exist within this github and within the KAIR github.

**Comment by claroche-r** [comment]
Hi @afm215,

You are right, we did not include the file "custom_blur_centered.mat" since it was too big. 
The file contains a blur kernel dataset built using this [paper](https://ieeexplore.ieee.org/document/6127172).

Here is the Google drive link to download the dataset: https://drive.google.com/file/d/1fDtSwItCCqob6ZJ_zvVfvQJ8U1q7dV7D/view?usp=share_link

You can also degrade your images using your own blur kernels if needed.

Thanks for your interest,
Charles

**Comment by afm215** [comment]
Hi @claroche-r,
Thank you very much for your quick answer.
If I may, it also seems that the coco data is also unavailable.
Do you know where I can get it?  

P.S: The github limit on large files can indeed be troublesome.
A way to bypass it is to use git-lfs : https://git-lfs.com/

**Comment by claroche-r** [comment]
For the download of COCO, I checked on their [website](https://cocodataset.org/#download) and it works on my side.

**Comment by afm215** [comment]
Thx a lot!
